apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-food
spec:
  replicas: 2
  template:
    metadata:
      name: pod-food
      labels:
        app: pod-food
    spec:
      containers:
        - name: pod-food-container
          image: carlohcs/food-repo:4
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cm-food
            - secretRef:
                name: secret-food
          # Necessário para autoscaling
          # -----
          # Segundo o Chat GPT, eis o necessário: 
          # - Comece com 0.5 CPU e 512Mi de memória para aplicações leves.
          # - Para aplicações de complexidade média, use 1 CPU e 1Gi de memória.
          # - Para aplicações pesadas, comece com 2 CPUs e 2Gi de memória, ajustando conforme necessário.
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
  selector:
    matchLabels:
      app: pod-food