apiVersion: v1
kind: Pod
metadata:
  name: pod-food
  labels:
    app: pod-food
spec:
  containers:
    - name: pod-food-container
      image: carlohcs/food-repo:4
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: cm-food
        - secretRef:
            name: secret-food
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"