name: Coverage

on: [push, pull_request]

# Descomente se precisar de uma nova branch para fazer alterações/testes
#on:
#  push:
#    branches:
#      - feat/add-coverage-info

jobs:
  coverage:
    permissions: write-all
    runs-on: ubuntu-latest
#    container: maven:3.8.1-openjdk-17-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          # cache-dependency-path: 'sub-project/pom.xml' # optional

      - name: Build and test with coverage
        run: mvn clean verify

      # Para evitar erros com permissão de escrita
      # https://stackoverflow.com/a/75250838/3929980
      # generates coverage-report.md and publishes as checkrun
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: /app/target/jacoco-report/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 0
          fail_below_threshold: false
          publish_only_summary: false

      # Publish Coverage Job Summary  # Optional
      - name: Add Jacocoo report to workflow run summary
        run: |
          echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage % | ${{ steps.jacoco_reporter.outputs.coverage_percentage }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :x: Number of Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Number of Lines | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY

      # uploads the coverage-report.md artifact  # Optional
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-markdown
          path: "*/coverage-results.md"
          retention-days: 90

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            food-main/target/jacoco-report/jacoco.csv
            food-cliente-core/target/jacoco-report/jacoco.csv

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'alfac@users.noreply.github.com'
            git add -A
            git commit -m "[GitHub Actions] Autogenerated JaCoCo coverage badge"
            git push
          fi
